#!/bin/bash -eu
## ====================================================================================================
##
## Copyright (c) 2024 Bengt Johansson <bengtj100 at gmail dot com>.
## All rights reserved.
##
## This software is part of the stacky project and its use is
## regulated by the conditions stipulated in the file named 'LICENCE',
## located in the top directory of said project.
##
## ====================================================================================================

readonly PNAME=$(basename "$0")
readonly PHOME=$(dirname "$0")
readonly COLS=$(( $(tput cols) - 1 ))

## ----------------------------------------------------------------------------------------------------

readonly PROJECT='stacky'

readonly SRC_DIR="${PHOME}/../src"
readonly BIN_DIR="${PHOME}/../bin"
readonly DOC_DIR="${PHOME}/../doc"
readonly PRELUDE="${PHOME}/../prelude"
readonly RELEASES="${PHOME}/../releases"

readonly CPU_ARCH=$(uname -m)
readonly KERNEL=$(uname -s)

## ====================================================================================================

function line
{
    awk -v "COLS=$COLS" 'BEGIN {for(i=0;i<COLS;i++)printf"%s","=";print}'
}

function message
{
    echo "$*"
    line
}

## ====================================================================================================

function getExecutable
{
    "$PHOME/get-executable"
}

## ----------------------------------------------------------------------------------------------------

function loadVersionInfo
{
    message "Loading version information"
    local executable=$(getExecutable)
    eval "$("$executable" --version)"
    echo "VERSION : $VERSION"
    echo "BUILD   : $BUILD"
    echo "GIT_TAG : $GIT_TAG"
    line
}

## ----------------------------------------------------------------------------------------------------

function setUpReleaseDirs
{
    message "Setting up the release directory"
    readonly THIS_RELEASE="${RELEASES}/${PROJECT}.${GIT_TAG}.${KERNEL}.${CPU_ARCH}"
    echo "THIS_RELEASE : $THIS_RELEASE"
    rm -rf "$THIS_RELEASE"
    mkdir -p "$THIS_RELEASE"
    line
}

## ----------------------------------------------------------------------------------------------------

function copyExecutable
{
    message "Copying executable to release"
    local executable=$(getExecutable)
    local binDir="$THIS_RELEASE/bin"
    mkdir -p "${binDir}"
    cp -p "${executable}" "${binDir}/"
}

## ----------------------------------------------------------------------------------------------------

function copyBinFiles
{
    message "Copying bin files to release"
    local binDir="$THIS_RELEASE/bin"
    mkdir -p "${binDir}"
    cp -p "${BIN_DIR}"/* "${binDir}/"
}

## ----------------------------------------------------------------------------------------------------

function copyLibFiles
{
    message "Copying lib files to release"
    local libDir="$THIS_RELEASE/lib/${PROJECT}"
    mkdir -p "${libDir}"
    cp -pPr "${PRELUDE}/" "${libDir}/"
}

## ----------------------------------------------------------------------------------------------------

function makeDocumentation
{
    message "Copying documentation files for release"
    local docDir="$THIS_RELEASE/doc"
    mkdir -p "$docDir"
    cp -pPv "${DOC_DIR}/"*.pdf "${docDir}"
    line
}

## ----------------------------------------------------------------------------------------------------

function makeTarBall
{
    message "Creating tar-ball"
    (
        cd "${RELEASES}"
        local relName="$(basename "${THIS_RELEASE}")"
        local tarBall="${relName}.tar.gz"
        echo "CWD      : $(pwd)"
        echo "REL-NAME : $relName"
        echo "TAR-BALL : $tarBall"
        rm -rf "${tarBall}"
        tar zcf "${tarBall}" "${relName}"
    )
    line
}

## ----------------------------------------------------------------------------------------------------

function cleanUp
{
    message "Cleaning up debris"
    rm -rf "${THIS_RELEASE}"
}

## ====================================================================================================

function main
{
    line

    loadVersionInfo
    setUpReleaseDirs
    copyExecutable
    copyBinFiles
    copyLibFiles
    makeDocumentation
    makeTarBall
    cleanUp

    message "Contents of the release dir"
    ls -1 "${RELEASES}"
    line

    message "THAT'S ALL FOLKS!"
}

main "$0"
